// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type MetricPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Cpu           []*CpuMetric           `protobuf:"bytes,3,rep,name=cpu,proto3" json:"cpu,omitempty"`
	Ram           []*RamMetric           `protobuf:"bytes,4,rep,name=ram,proto3" json:"ram,omitempty"`
	Disk          []*DiskMetric          `protobuf:"bytes,5,rep,name=disk,proto3" json:"disk,omitempty"`
	Network       []*NetworkMetric       `protobuf:"bytes,6,rep,name=network,proto3" json:"network,omitempty"`
	Docker        []*DockerMetric        `protobuf:"bytes,7,rep,name=docker,proto3" json:"docker,omitempty"`
	Database      []*DatabaseMetric      `protobuf:"bytes,8,rep,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *MetricPayload) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *MetricPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricPayload) GetCpu() []*CpuMetric {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricPayload) GetRam() []*RamMetric {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *MetricPayload) GetDisk() []*DiskMetric {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *MetricPayload) GetNetwork() []*NetworkMetric {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *MetricPayload) GetDocker() []*DockerMetric {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *MetricPayload) GetDatabase() []*DatabaseMetric {
	if x != nil {
		return x.Database
	}
	return nil
}

type CpuMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent  float32                `protobuf:"fixed32,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetric) Reset() {
	*x = CpuMetric{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetric) ProtoMessage() {}

func (x *CpuMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetric.ProtoReflect.Descriptor instead.
func (*CpuMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CpuMetric) GetUsagePercent() float32 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type RamMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     int64                  `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RamMetric) Reset() {
	*x = RamMetric{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RamMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RamMetric) ProtoMessage() {}

func (x *RamMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RamMetric.ProtoReflect.Descriptor instead.
func (*RamMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RamMetric) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *RamMetric) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type DiskMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	UsedBytes     int64                  `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetric) Reset() {
	*x = DiskMetric{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetric) ProtoMessage() {}

func (x *DiskMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetric.ProtoReflect.Descriptor instead.
func (*DiskMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DiskMetric) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetric) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetric) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type NetworkMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	RxBytes       int64                  `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       int64                  `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetric) Reset() {
	*x = NetworkMetric{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetric) ProtoMessage() {}

func (x *NetworkMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetric.ProtoReflect.Descriptor instead.
func (*NetworkMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkMetric) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *NetworkMetric) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkMetric) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

type DockerMetric struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DockerHashId    string                 `protobuf:"bytes,1,opt,name=docker_hash_id,json=dockerHashId,proto3" json:"docker_hash_id,omitempty"` // 64-char container ID from Docker
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                       // To auto-create the container in DB if missing
	Image           string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State           string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CpuUsagePercent float32                `protobuf:"fixed32,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RamUsedBytes    int64                  `protobuf:"varint,6,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DockerMetric) Reset() {
	*x = DockerMetric{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerMetric) ProtoMessage() {}

func (x *DockerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerMetric.ProtoReflect.Descriptor instead.
func (*DockerMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DockerMetric) GetDockerHashId() string {
	if x != nil {
		return x.DockerHashId
	}
	return ""
}

func (x *DockerMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DockerMetric) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DockerMetric) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DockerMetric) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *DockerMetric) GetRamUsedBytes() int64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

type StreamMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsResponse) Reset() {
	*x = StreamMetricsResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsResponse) ProtoMessage() {}

func (x *StreamMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsResponse.ProtoReflect.Descriptor instead.
func (*StreamMetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StreamMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DatabaseMetric struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DbId           string                 `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty"`       // User-defined ID for this DB
	DbType         string                 `protobuf:"bytes,2,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"` // postgres, mssql, oracle
	Host           string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tps            float32                `protobuf:"fixed32,5,opt,name=tps,proto3" json:"tps,omitempty"` // Transactions per second
	ActiveSessions int32                  `protobuf:"varint,6,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	IdleSessions   int32                  `protobuf:"varint,7,opt,name=idle_sessions,json=idleSessions,proto3" json:"idle_sessions,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CacheHitRatio  float32                `protobuf:"fixed32,9,opt,name=cache_hit_ratio,json=cacheHitRatio,proto3" json:"cache_hit_ratio,omitempty"`
	Tables         []*TableMetric         `protobuf:"bytes,10,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DatabaseMetric) Reset() {
	*x = DatabaseMetric{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseMetric) ProtoMessage() {}

func (x *DatabaseMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseMetric.ProtoReflect.Descriptor instead.
func (*DatabaseMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DatabaseMetric) GetDbId() string {
	if x != nil {
		return x.DbId
	}
	return ""
}

func (x *DatabaseMetric) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *DatabaseMetric) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseMetric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DatabaseMetric) GetTps() float32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DatabaseMetric) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *DatabaseMetric) GetIdleSessions() int32 {
	if x != nil {
		return x.IdleSessions
	}
	return 0
}

func (x *DatabaseMetric) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DatabaseMetric) GetCacheHitRatio() float32 {
	if x != nil {
		return x.CacheHitRatio
	}
	return 0
}

func (x *DatabaseMetric) GetTables() []*TableMetric {
	if x != nil {
		return x.Tables
	}
	return nil
}

type TableMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	RowCount      int64                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableMetric) Reset() {
	*x = TableMetric{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMetric) ProtoMessage() {}

func (x *TableMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMetric.ProtoReflect.Descriptor instead.
func (*TableMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *TableMetric) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableMetric) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *TableMetric) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bagent.v1\"\\\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\"E\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"E\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xd9\x02\n" +
	"\rMetricPayload\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x03cpu\x18\x03 \x03(\v2\x13.agent.v1.CpuMetricR\x03cpu\x12%\n" +
	"\x03ram\x18\x04 \x03(\v2\x13.agent.v1.RamMetricR\x03ram\x12(\n" +
	"\x04disk\x18\x05 \x03(\v2\x14.agent.v1.DiskMetricR\x04disk\x121\n" +
	"\anetwork\x18\x06 \x03(\v2\x17.agent.v1.NetworkMetricR\anetwork\x12.\n" +
	"\x06docker\x18\a \x03(\v2\x16.agent.v1.DockerMetricR\x06docker\x124\n" +
	"\bdatabase\x18\b \x03(\v2\x18.agent.v1.DatabaseMetricR\bdatabase\"0\n" +
	"\tCpuMetric\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x02R\fusagePercent\"K\n" +
	"\tRamMetric\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\"d\n" +
	"\n" +
	"DiskMetric\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\"c\n" +
	"\rNetworkMetric\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x03R\atxBytes\"\xc6\x01\n" +
	"\fDockerMetric\x12$\n" +
	"\x0edocker_hash_id\x18\x01 \x01(\tR\fdockerHashId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x02R\x0fcpuUsagePercent\x12$\n" +
	"\x0eram_used_bytes\x18\x06 \x01(\x03R\framUsedBytes\"1\n" +
	"\x15StreamMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc6\x02\n" +
	"\x0eDatabaseMetric\x12\x13\n" +
	"\x05db_id\x18\x01 \x01(\tR\x04dbId\x12\x17\n" +
	"\adb_type\x18\x02 \x01(\tR\x06dbType\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03tps\x18\x05 \x01(\x02R\x03tps\x12'\n" +
	"\x0factive_sessions\x18\x06 \x01(\x05R\x0eactiveSessions\x12#\n" +
	"\ridle_sessions\x18\a \x01(\x05R\fidleSessions\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\b \x01(\x03R\tsizeBytes\x12&\n" +
	"\x0fcache_hit_ratio\x18\t \x01(\x02R\rcacheHitRatio\x12-\n" +
	"\x06tables\x18\n" +
	" \x03(\v2\x15.agent.v1.TableMetricR\x06tables\"h\n" +
	"\vTableMetric\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x03R\browCount2\xe4\x01\n" +
	"\fAgentService\x12A\n" +
	"\bRegister\x12\x19.agent.v1.RegisterRequest\x1a\x1a.agent.v1.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.agent.v1.HeartbeatRequest\x1a\x1b.agent.v1.HeartbeatResponse\x12K\n" +
	"\rStreamMetrics\x12\x17.agent.v1.MetricPayload\x1a\x1f.agent.v1.StreamMetricsResponse(\x01B%Z#re-backend/scraper/proto/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: agent.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 2: agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: agent.v1.HeartbeatResponse
	(*MetricPayload)(nil),         // 4: agent.v1.MetricPayload
	(*CpuMetric)(nil),             // 5: agent.v1.CpuMetric
	(*RamMetric)(nil),             // 6: agent.v1.RamMetric
	(*DiskMetric)(nil),            // 7: agent.v1.DiskMetric
	(*NetworkMetric)(nil),         // 8: agent.v1.NetworkMetric
	(*DockerMetric)(nil),          // 9: agent.v1.DockerMetric
	(*StreamMetricsResponse)(nil), // 10: agent.v1.StreamMetricsResponse
	(*DatabaseMetric)(nil),        // 11: agent.v1.DatabaseMetric
	(*TableMetric)(nil),           // 12: agent.v1.TableMetric
}
var file_agent_proto_depIdxs = []int32{
	5,  // 0: agent.v1.MetricPayload.cpu:type_name -> agent.v1.CpuMetric
	6,  // 1: agent.v1.MetricPayload.ram:type_name -> agent.v1.RamMetric
	7,  // 2: agent.v1.MetricPayload.disk:type_name -> agent.v1.DiskMetric
	8,  // 3: agent.v1.MetricPayload.network:type_name -> agent.v1.NetworkMetric
	9,  // 4: agent.v1.MetricPayload.docker:type_name -> agent.v1.DockerMetric
	11, // 5: agent.v1.MetricPayload.database:type_name -> agent.v1.DatabaseMetric
	12, // 6: agent.v1.DatabaseMetric.tables:type_name -> agent.v1.TableMetric
	0,  // 7: agent.v1.AgentService.Register:input_type -> agent.v1.RegisterRequest
	2,  // 8: agent.v1.AgentService.Heartbeat:input_type -> agent.v1.HeartbeatRequest
	4,  // 9: agent.v1.AgentService.StreamMetrics:input_type -> agent.v1.MetricPayload
	1,  // 10: agent.v1.AgentService.Register:output_type -> agent.v1.RegisterResponse
	3,  // 11: agent.v1.AgentService.Heartbeat:output_type -> agent.v1.HeartbeatResponse
	10, // 12: agent.v1.AgentService.StreamMetrics:output_type -> agent.v1.StreamMetricsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
