// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    hostname,
    ip_address,
    port,
    status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, hostname, ip_address, port, status, created_at, updated_at
`

type CreateAssetParams struct {
	Hostname  string      `json:"hostname"`
	IpAddress string      `json:"ip_address"`
	Port      pgtype.Int4 `json:"port"`
	Status    pgtype.Text `json:"status"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.Hostname,
		arg.IpAddress,
		arg.Port,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.Port,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContainer = `-- name: CreateContainer :one
INSERT INTO containers (
    asset_id,
    docker_container_id,
    name,
    image,
    state
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, asset_id, docker_container_id, name, image, state, created_at
`

type CreateContainerParams struct {
	AssetID           pgtype.UUID `json:"asset_id"`
	DockerContainerID string      `json:"docker_container_id"`
	Name              string      `json:"name"`
	Image             pgtype.Text `json:"image"`
	State             pgtype.Text `json:"state"`
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, createContainer,
		arg.AssetID,
		arg.DockerContainerID,
		arg.Name,
		arg.Image,
		arg.State,
	)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.DockerContainerID,
		&i.Name,
		&i.Image,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM containers WHERE id = $1
`

func (q *Queries) DeleteContainer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContainer, id)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, hostname, ip_address, port, status, created_at, updated_at FROM assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.Port,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContainerByDockerID = `-- name: GetContainerByDockerID :one
SELECT id, asset_id, docker_container_id, name, image, state, created_at FROM containers WHERE docker_container_id = $1
`

func (q *Queries) GetContainerByDockerID(ctx context.Context, dockerContainerID string) (Container, error) {
	row := q.db.QueryRow(ctx, getContainerByDockerID, dockerContainerID)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.DockerContainerID,
		&i.Name,
		&i.Image,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, hostname, ip_address, port, status, created_at, updated_at FROM assets ORDER BY created_at DESC
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.Port,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainersByAsset = `-- name: ListContainersByAsset :many
SELECT id, asset_id, docker_container_id, name, image, state, created_at FROM containers WHERE asset_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListContainersByAsset(ctx context.Context, assetID pgtype.UUID) ([]Container, error) {
	rows, err := q.db.Query(ctx, listContainersByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.DockerContainerID,
			&i.Name,
			&i.Image,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetStatus = `-- name: UpdateAssetStatus :exec
UPDATE assets SET status = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type UpdateAssetStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error {
	_, err := q.db.Exec(ctx, updateAssetStatus, arg.ID, arg.Status)
	return err
}

const updateContainerState = `-- name: UpdateContainerState :exec
UPDATE containers SET state = $2 WHERE id = $1
`

type UpdateContainerStateParams struct {
	ID    pgtype.UUID `json:"id"`
	State pgtype.Text `json:"state"`
}

func (q *Queries) UpdateContainerState(ctx context.Context, arg UpdateContainerStateParams) error {
	_, err := q.db.Exec(ctx, updateContainerState, arg.ID, arg.State)
	return err
}
