// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertCpuRaw implements pgx.CopyFromSource.
type iteratorForInsertCpuRaw struct {
	rows                 []InsertCpuRawParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCpuRaw) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCpuRaw) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Time,
		r.rows[0].AssetID,
		r.rows[0].UsagePercent,
	}, nil
}

func (r iteratorForInsertCpuRaw) Err() error {
	return nil
}

func (q *Queries) InsertCpuRaw(ctx context.Context, arg []InsertCpuRawParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metrics_cpu_raw"}, []string{"time", "asset_id", "usage_percent"}, &iteratorForInsertCpuRaw{rows: arg})
}

// iteratorForInsertDiskRaw implements pgx.CopyFromSource.
type iteratorForInsertDiskRaw struct {
	rows                 []InsertDiskRawParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDiskRaw) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDiskRaw) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Time,
		r.rows[0].AssetID,
		r.rows[0].Device,
		r.rows[0].UsedBytes,
		r.rows[0].TotalBytes,
	}, nil
}

func (r iteratorForInsertDiskRaw) Err() error {
	return nil
}

func (q *Queries) InsertDiskRaw(ctx context.Context, arg []InsertDiskRawParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metrics_disk_raw"}, []string{"time", "asset_id", "device", "used_bytes", "total_bytes"}, &iteratorForInsertDiskRaw{rows: arg})
}

// iteratorForInsertDockerRaw implements pgx.CopyFromSource.
type iteratorForInsertDockerRaw struct {
	rows                 []InsertDockerRawParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDockerRaw) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDockerRaw) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Time,
		r.rows[0].ContainerID,
		r.rows[0].CpuUsagePercent,
		r.rows[0].RamUsedBytes,
	}, nil
}

func (r iteratorForInsertDockerRaw) Err() error {
	return nil
}

func (q *Queries) InsertDockerRaw(ctx context.Context, arg []InsertDockerRawParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metrics_docker_raw"}, []string{"time", "container_id", "cpu_usage_percent", "ram_used_bytes"}, &iteratorForInsertDockerRaw{rows: arg})
}

// iteratorForInsertNetworkRaw implements pgx.CopyFromSource.
type iteratorForInsertNetworkRaw struct {
	rows                 []InsertNetworkRawParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertNetworkRaw) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertNetworkRaw) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Time,
		r.rows[0].AssetID,
		r.rows[0].Interface,
		r.rows[0].RxBytes,
		r.rows[0].TxBytes,
	}, nil
}

func (r iteratorForInsertNetworkRaw) Err() error {
	return nil
}

func (q *Queries) InsertNetworkRaw(ctx context.Context, arg []InsertNetworkRawParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metrics_network_raw"}, []string{"time", "asset_id", "interface", "rx_bytes", "tx_bytes"}, &iteratorForInsertNetworkRaw{rows: arg})
}

// iteratorForInsertRamRaw implements pgx.CopyFromSource.
type iteratorForInsertRamRaw struct {
	rows                 []InsertRamRawParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRamRaw) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRamRaw) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Time,
		r.rows[0].AssetID,
		r.rows[0].UsedBytes,
		r.rows[0].TotalBytes,
	}, nil
}

func (r iteratorForInsertRamRaw) Err() error {
	return nil
}

func (q *Queries) InsertRamRaw(ctx context.Context, arg []InsertRamRawParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metrics_ram_raw"}, []string{"time", "asset_id", "used_bytes", "total_bytes"}, &iteratorForInsertRamRaw{rows: arg})
}
