// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateCpuRawTo10m = `-- name: AggregateCpuRawTo10m :exec
WITH lagged AS (
  SELECT time, asset_id, usage_percent,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_cpu_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_cpu_10m (time_bucket, asset_id, avg_usage_percent, min_usage_percent, max_usage_percent, wavg_usage_percent)
SELECT $1, asset_id, COALESCE(AVG(usage_percent), 0)::real, COALESCE(MIN(usage_percent), 0)::real, COALESCE(MAX(usage_percent), 0)::real, COALESCE((SUM(usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real
FROM lagged
GROUP BY 1, 2
`

type AggregateCpuRawTo10mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateCpuRawTo10m(ctx context.Context, arg AggregateCpuRawTo10mParams) error {
	_, err := q.db.Exec(ctx, aggregateCpuRawTo10m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateCpuRawTo1d = `-- name: AggregateCpuRawTo1d :exec
WITH lagged AS (
  SELECT time, asset_id, usage_percent,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_cpu_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_cpu_1d (time_bucket, asset_id, avg_usage_percent, min_usage_percent, max_usage_percent, wavg_usage_percent)
SELECT $1, asset_id, COALESCE(AVG(usage_percent), 0)::real, COALESCE(MIN(usage_percent), 0)::real, COALESCE(MAX(usage_percent), 0)::real, COALESCE((SUM(usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real
FROM lagged
GROUP BY 1, 2
`

type AggregateCpuRawTo1dParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateCpuRawTo1d(ctx context.Context, arg AggregateCpuRawTo1dParams) error {
	_, err := q.db.Exec(ctx, aggregateCpuRawTo1d, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateCpuRawTo1h = `-- name: AggregateCpuRawTo1h :exec
WITH lagged AS (
  SELECT time, asset_id, usage_percent,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_cpu_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_cpu_1h (time_bucket, asset_id, avg_usage_percent, min_usage_percent, max_usage_percent, wavg_usage_percent)
SELECT $1, asset_id, COALESCE(AVG(usage_percent), 0)::real, COALESCE(MIN(usage_percent), 0)::real, COALESCE(MAX(usage_percent), 0)::real, COALESCE((SUM(usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real
FROM lagged
GROUP BY 1, 2
`

type AggregateCpuRawTo1hParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateCpuRawTo1h(ctx context.Context, arg AggregateCpuRawTo1hParams) error {
	_, err := q.db.Exec(ctx, aggregateCpuRawTo1h, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateCpuRawTo1m = `-- name: AggregateCpuRawTo1m :exec
WITH lagged AS (
  SELECT time, asset_id, usage_percent,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_cpu_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_cpu_1m (time_bucket, asset_id, avg_usage_percent, min_usage_percent, max_usage_percent, wavg_usage_percent)
SELECT $1, asset_id, COALESCE(AVG(usage_percent), 0)::real, COALESCE(MIN(usage_percent), 0)::real, COALESCE(MAX(usage_percent), 0)::real, COALESCE((SUM(usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real
FROM lagged
GROUP BY 1, 2
`

type AggregateCpuRawTo1mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateCpuRawTo1m(ctx context.Context, arg AggregateCpuRawTo1mParams) error {
	_, err := q.db.Exec(ctx, aggregateCpuRawTo1m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateCpuRawTo5m = `-- name: AggregateCpuRawTo5m :exec
WITH lagged AS (
  SELECT time, asset_id, usage_percent,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_cpu_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_cpu_5m (time_bucket, asset_id, avg_usage_percent, min_usage_percent, max_usage_percent, wavg_usage_percent)
SELECT $1, asset_id, COALESCE(AVG(usage_percent), 0)::real, COALESCE(MIN(usage_percent), 0)::real, COALESCE(MAX(usage_percent), 0)::real, COALESCE((SUM(usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real
FROM lagged
GROUP BY 1, 2
`

type AggregateCpuRawTo5mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateCpuRawTo5m(ctx context.Context, arg AggregateCpuRawTo5mParams) error {
	_, err := q.db.Exec(ctx, aggregateCpuRawTo5m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDiskRawTo10m = `-- name: AggregateDiskRawTo10m :exec
WITH lagged AS (
  SELECT time, asset_id, device, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, device ORDER BY time))) AS duration
  FROM metrics_disk_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_disk_10m (time_bucket, asset_id, device, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, device, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateDiskRawTo10mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDiskRawTo10m(ctx context.Context, arg AggregateDiskRawTo10mParams) error {
	_, err := q.db.Exec(ctx, aggregateDiskRawTo10m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDiskRawTo1d = `-- name: AggregateDiskRawTo1d :exec
WITH lagged AS (
  SELECT time, asset_id, device, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, device ORDER BY time))) AS duration
  FROM metrics_disk_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_disk_1d (time_bucket, asset_id, device, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, device, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateDiskRawTo1dParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDiskRawTo1d(ctx context.Context, arg AggregateDiskRawTo1dParams) error {
	_, err := q.db.Exec(ctx, aggregateDiskRawTo1d, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDiskRawTo1h = `-- name: AggregateDiskRawTo1h :exec
WITH lagged AS (
  SELECT time, asset_id, device, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, device ORDER BY time))) AS duration
  FROM metrics_disk_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_disk_1h (time_bucket, asset_id, device, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, device, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateDiskRawTo1hParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDiskRawTo1h(ctx context.Context, arg AggregateDiskRawTo1hParams) error {
	_, err := q.db.Exec(ctx, aggregateDiskRawTo1h, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDiskRawTo1m = `-- name: AggregateDiskRawTo1m :exec
WITH lagged AS (
  SELECT time, asset_id, device, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, device ORDER BY time))) AS duration
  FROM metrics_disk_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_disk_1m (time_bucket, asset_id, device, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, device, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateDiskRawTo1mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDiskRawTo1m(ctx context.Context, arg AggregateDiskRawTo1mParams) error {
	_, err := q.db.Exec(ctx, aggregateDiskRawTo1m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDiskRawTo5m = `-- name: AggregateDiskRawTo5m :exec
WITH lagged AS (
  SELECT time, asset_id, device, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, device ORDER BY time))) AS duration
  FROM metrics_disk_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_disk_5m (time_bucket, asset_id, device, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, device, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateDiskRawTo5mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDiskRawTo5m(ctx context.Context, arg AggregateDiskRawTo5mParams) error {
	_, err := q.db.Exec(ctx, aggregateDiskRawTo5m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDockerRawTo10m = `-- name: AggregateDockerRawTo10m :exec
WITH lagged AS (
  SELECT time, container_id, cpu_usage_percent, ram_used_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY container_id ORDER BY time))) AS duration
  FROM metrics_docker_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_docker_10m (time_bucket, container_id, avg_cpu_usage_percent, min_cpu_usage_percent, max_cpu_usage_percent, wavg_cpu_usage_percent, avg_ram_used_bytes, min_ram_used_bytes, max_ram_used_bytes, wavg_ram_used_bytes)
SELECT $1, container_id, COALESCE(AVG(cpu_usage_percent), 0)::real, COALESCE(MIN(cpu_usage_percent), 0)::real, COALESCE(MAX(cpu_usage_percent), 0)::real, COALESCE((SUM(cpu_usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real, COALESCE(AVG(ram_used_bytes), 0)::bigint, COALESCE(MIN(ram_used_bytes), 0)::bigint, COALESCE(MAX(ram_used_bytes), 0)::bigint, COALESCE((SUM(ram_used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateDockerRawTo10mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDockerRawTo10m(ctx context.Context, arg AggregateDockerRawTo10mParams) error {
	_, err := q.db.Exec(ctx, aggregateDockerRawTo10m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDockerRawTo1d = `-- name: AggregateDockerRawTo1d :exec
WITH lagged AS (
  SELECT time, container_id, cpu_usage_percent, ram_used_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY container_id ORDER BY time))) AS duration
  FROM metrics_docker_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_docker_1d (time_bucket, container_id, avg_cpu_usage_percent, min_cpu_usage_percent, max_cpu_usage_percent, wavg_cpu_usage_percent, avg_ram_used_bytes, min_ram_used_bytes, max_ram_used_bytes, wavg_ram_used_bytes)
SELECT $1, container_id, COALESCE(AVG(cpu_usage_percent), 0)::real, COALESCE(MIN(cpu_usage_percent), 0)::real, COALESCE(MAX(cpu_usage_percent), 0)::real, COALESCE((SUM(cpu_usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real, COALESCE(AVG(ram_used_bytes), 0)::bigint, COALESCE(MIN(ram_used_bytes), 0)::bigint, COALESCE(MAX(ram_used_bytes), 0)::bigint, COALESCE((SUM(ram_used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateDockerRawTo1dParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDockerRawTo1d(ctx context.Context, arg AggregateDockerRawTo1dParams) error {
	_, err := q.db.Exec(ctx, aggregateDockerRawTo1d, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDockerRawTo1h = `-- name: AggregateDockerRawTo1h :exec
WITH lagged AS (
  SELECT time, container_id, cpu_usage_percent, ram_used_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY container_id ORDER BY time))) AS duration
  FROM metrics_docker_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_docker_1h (time_bucket, container_id, avg_cpu_usage_percent, min_cpu_usage_percent, max_cpu_usage_percent, wavg_cpu_usage_percent, avg_ram_used_bytes, min_ram_used_bytes, max_ram_used_bytes, wavg_ram_used_bytes)
SELECT $1, container_id, COALESCE(AVG(cpu_usage_percent), 0)::real, COALESCE(MIN(cpu_usage_percent), 0)::real, COALESCE(MAX(cpu_usage_percent), 0)::real, COALESCE((SUM(cpu_usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real, COALESCE(AVG(ram_used_bytes), 0)::bigint, COALESCE(MIN(ram_used_bytes), 0)::bigint, COALESCE(MAX(ram_used_bytes), 0)::bigint, COALESCE((SUM(ram_used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateDockerRawTo1hParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDockerRawTo1h(ctx context.Context, arg AggregateDockerRawTo1hParams) error {
	_, err := q.db.Exec(ctx, aggregateDockerRawTo1h, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDockerRawTo1m = `-- name: AggregateDockerRawTo1m :exec
WITH lagged AS (
  SELECT time, container_id, cpu_usage_percent, ram_used_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY container_id ORDER BY time))) AS duration
  FROM metrics_docker_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_docker_1m (time_bucket, container_id, avg_cpu_usage_percent, min_cpu_usage_percent, max_cpu_usage_percent, wavg_cpu_usage_percent, avg_ram_used_bytes, min_ram_used_bytes, max_ram_used_bytes, wavg_ram_used_bytes)
SELECT $1, container_id, COALESCE(AVG(cpu_usage_percent), 0)::real, COALESCE(MIN(cpu_usage_percent), 0)::real, COALESCE(MAX(cpu_usage_percent), 0)::real, COALESCE((SUM(cpu_usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real, COALESCE(AVG(ram_used_bytes), 0)::bigint, COALESCE(MIN(ram_used_bytes), 0)::bigint, COALESCE(MAX(ram_used_bytes), 0)::bigint, COALESCE((SUM(ram_used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateDockerRawTo1mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDockerRawTo1m(ctx context.Context, arg AggregateDockerRawTo1mParams) error {
	_, err := q.db.Exec(ctx, aggregateDockerRawTo1m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateDockerRawTo5m = `-- name: AggregateDockerRawTo5m :exec
WITH lagged AS (
  SELECT time, container_id, cpu_usage_percent, ram_used_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY container_id ORDER BY time))) AS duration
  FROM metrics_docker_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_docker_5m (time_bucket, container_id, avg_cpu_usage_percent, min_cpu_usage_percent, max_cpu_usage_percent, wavg_cpu_usage_percent, avg_ram_used_bytes, min_ram_used_bytes, max_ram_used_bytes, wavg_ram_used_bytes)
SELECT $1, container_id, COALESCE(AVG(cpu_usage_percent), 0)::real, COALESCE(MIN(cpu_usage_percent), 0)::real, COALESCE(MAX(cpu_usage_percent), 0)::real, COALESCE((SUM(cpu_usage_percent * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::real, COALESCE(AVG(ram_used_bytes), 0)::bigint, COALESCE(MIN(ram_used_bytes), 0)::bigint, COALESCE(MAX(ram_used_bytes), 0)::bigint, COALESCE((SUM(ram_used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateDockerRawTo5mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateDockerRawTo5m(ctx context.Context, arg AggregateDockerRawTo5mParams) error {
	_, err := q.db.Exec(ctx, aggregateDockerRawTo5m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateNetworkRawTo10m = `-- name: AggregateNetworkRawTo10m :exec
WITH lagged AS (
  SELECT time, asset_id, interface, rx_bytes, tx_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, interface ORDER BY time))) AS duration
  FROM metrics_network_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_network_10m (time_bucket, asset_id, interface, avg_rx_bytes, min_rx_bytes, max_rx_bytes, wavg_rx_bytes, avg_tx_bytes, min_tx_bytes, max_tx_bytes, wavg_tx_bytes)
SELECT $1, asset_id, interface, COALESCE(AVG(rx_bytes), 0)::bigint, COALESCE(MIN(rx_bytes), 0)::bigint, COALESCE(MAX(rx_bytes), 0)::bigint, COALESCE((SUM(rx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(tx_bytes), 0)::bigint, COALESCE(MIN(tx_bytes), 0)::bigint, COALESCE(MAX(tx_bytes), 0)::bigint, COALESCE((SUM(tx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateNetworkRawTo10mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateNetworkRawTo10m(ctx context.Context, arg AggregateNetworkRawTo10mParams) error {
	_, err := q.db.Exec(ctx, aggregateNetworkRawTo10m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateNetworkRawTo1d = `-- name: AggregateNetworkRawTo1d :exec
WITH lagged AS (
  SELECT time, asset_id, interface, rx_bytes, tx_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, interface ORDER BY time))) AS duration
  FROM metrics_network_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_network_1d (time_bucket, asset_id, interface, avg_rx_bytes, min_rx_bytes, max_rx_bytes, wavg_rx_bytes, avg_tx_bytes, min_tx_bytes, max_tx_bytes, wavg_tx_bytes)
SELECT $1, asset_id, interface, COALESCE(AVG(rx_bytes), 0)::bigint, COALESCE(MIN(rx_bytes), 0)::bigint, COALESCE(MAX(rx_bytes), 0)::bigint, COALESCE((SUM(rx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(tx_bytes), 0)::bigint, COALESCE(MIN(tx_bytes), 0)::bigint, COALESCE(MAX(tx_bytes), 0)::bigint, COALESCE((SUM(tx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateNetworkRawTo1dParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateNetworkRawTo1d(ctx context.Context, arg AggregateNetworkRawTo1dParams) error {
	_, err := q.db.Exec(ctx, aggregateNetworkRawTo1d, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateNetworkRawTo1h = `-- name: AggregateNetworkRawTo1h :exec
WITH lagged AS (
  SELECT time, asset_id, interface, rx_bytes, tx_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, interface ORDER BY time))) AS duration
  FROM metrics_network_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_network_1h (time_bucket, asset_id, interface, avg_rx_bytes, min_rx_bytes, max_rx_bytes, wavg_rx_bytes, avg_tx_bytes, min_tx_bytes, max_tx_bytes, wavg_tx_bytes)
SELECT $1, asset_id, interface, COALESCE(AVG(rx_bytes), 0)::bigint, COALESCE(MIN(rx_bytes), 0)::bigint, COALESCE(MAX(rx_bytes), 0)::bigint, COALESCE((SUM(rx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(tx_bytes), 0)::bigint, COALESCE(MIN(tx_bytes), 0)::bigint, COALESCE(MAX(tx_bytes), 0)::bigint, COALESCE((SUM(tx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateNetworkRawTo1hParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateNetworkRawTo1h(ctx context.Context, arg AggregateNetworkRawTo1hParams) error {
	_, err := q.db.Exec(ctx, aggregateNetworkRawTo1h, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateNetworkRawTo1m = `-- name: AggregateNetworkRawTo1m :exec
WITH lagged AS (
  SELECT time, asset_id, interface, rx_bytes, tx_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, interface ORDER BY time))) AS duration
  FROM metrics_network_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_network_1m (time_bucket, asset_id, interface, avg_rx_bytes, min_rx_bytes, max_rx_bytes, wavg_rx_bytes, avg_tx_bytes, min_tx_bytes, max_tx_bytes, wavg_tx_bytes)
SELECT $1, asset_id, interface, COALESCE(AVG(rx_bytes), 0)::bigint, COALESCE(MIN(rx_bytes), 0)::bigint, COALESCE(MAX(rx_bytes), 0)::bigint, COALESCE((SUM(rx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(tx_bytes), 0)::bigint, COALESCE(MIN(tx_bytes), 0)::bigint, COALESCE(MAX(tx_bytes), 0)::bigint, COALESCE((SUM(tx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateNetworkRawTo1mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateNetworkRawTo1m(ctx context.Context, arg AggregateNetworkRawTo1mParams) error {
	_, err := q.db.Exec(ctx, aggregateNetworkRawTo1m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateNetworkRawTo5m = `-- name: AggregateNetworkRawTo5m :exec
WITH lagged AS (
  SELECT time, asset_id, interface, rx_bytes, tx_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id, interface ORDER BY time))) AS duration
  FROM metrics_network_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_network_5m (time_bucket, asset_id, interface, avg_rx_bytes, min_rx_bytes, max_rx_bytes, wavg_rx_bytes, avg_tx_bytes, min_tx_bytes, max_tx_bytes, wavg_tx_bytes)
SELECT $1, asset_id, interface, COALESCE(AVG(rx_bytes), 0)::bigint, COALESCE(MIN(rx_bytes), 0)::bigint, COALESCE(MAX(rx_bytes), 0)::bigint, COALESCE((SUM(rx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(tx_bytes), 0)::bigint, COALESCE(MIN(tx_bytes), 0)::bigint, COALESCE(MAX(tx_bytes), 0)::bigint, COALESCE((SUM(tx_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2, 3
`

type AggregateNetworkRawTo5mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateNetworkRawTo5m(ctx context.Context, arg AggregateNetworkRawTo5mParams) error {
	_, err := q.db.Exec(ctx, aggregateNetworkRawTo5m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateRamRawTo10m = `-- name: AggregateRamRawTo10m :exec
WITH lagged AS (
  SELECT time, asset_id, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_ram_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_ram_10m (time_bucket, asset_id, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateRamRawTo10mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateRamRawTo10m(ctx context.Context, arg AggregateRamRawTo10mParams) error {
	_, err := q.db.Exec(ctx, aggregateRamRawTo10m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateRamRawTo1d = `-- name: AggregateRamRawTo1d :exec
WITH lagged AS (
  SELECT time, asset_id, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_ram_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_ram_1d (time_bucket, asset_id, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateRamRawTo1dParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateRamRawTo1d(ctx context.Context, arg AggregateRamRawTo1dParams) error {
	_, err := q.db.Exec(ctx, aggregateRamRawTo1d, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateRamRawTo1h = `-- name: AggregateRamRawTo1h :exec
WITH lagged AS (
  SELECT time, asset_id, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_ram_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_ram_1h (time_bucket, asset_id, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateRamRawTo1hParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateRamRawTo1h(ctx context.Context, arg AggregateRamRawTo1hParams) error {
	_, err := q.db.Exec(ctx, aggregateRamRawTo1h, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateRamRawTo1m = `-- name: AggregateRamRawTo1m :exec
WITH lagged AS (
  SELECT time, asset_id, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_ram_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_ram_1m (time_bucket, asset_id, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateRamRawTo1mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateRamRawTo1m(ctx context.Context, arg AggregateRamRawTo1mParams) error {
	_, err := q.db.Exec(ctx, aggregateRamRawTo1m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const aggregateRamRawTo5m = `-- name: AggregateRamRawTo5m :exec
WITH lagged AS (
  SELECT time, asset_id, used_bytes, total_bytes,
         EXTRACT(EPOCH FROM (time - LAG(time) OVER (PARTITION BY asset_id ORDER BY time))) AS duration
  FROM metrics_ram_raw
  WHERE time >= $2 AND time < $3
)
INSERT INTO metrics_ram_5m (time_bucket, asset_id, avg_used_bytes, min_used_bytes, max_used_bytes, wavg_used_bytes, avg_total_bytes, min_total_bytes, max_total_bytes, wavg_total_bytes)
SELECT $1, asset_id, COALESCE(AVG(used_bytes), 0)::bigint, COALESCE(MIN(used_bytes), 0)::bigint, COALESCE(MAX(used_bytes), 0)::bigint, COALESCE((SUM(used_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint, COALESCE(AVG(total_bytes), 0)::bigint, COALESCE(MIN(total_bytes), 0)::bigint, COALESCE(MAX(total_bytes), 0)::bigint, COALESCE((SUM(total_bytes * COALESCE(duration, 1)) / NULLIF(SUM(COALESCE(duration, 1)), 0)), 0)::bigint
FROM lagged
GROUP BY 1, 2
`

type AggregateRamRawTo5mParams struct {
	TimeBucket pgtype.Timestamptz `json:"time_bucket"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) AggregateRamRawTo5m(ctx context.Context, arg AggregateRamRawTo5mParams) error {
	_, err := q.db.Exec(ctx, aggregateRamRawTo5m, arg.TimeBucket, arg.StartTime, arg.EndTime)
	return err
}

const deleteOldCpu10m = `-- name: DeleteOldCpu10m :exec
DELETE FROM metrics_cpu_10m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldCpu10m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldCpu10m, threshold)
	return err
}

const deleteOldCpu1d = `-- name: DeleteOldCpu1d :exec
DELETE FROM metrics_cpu_1d WHERE time_bucket < $1
`

func (q *Queries) DeleteOldCpu1d(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldCpu1d, threshold)
	return err
}

const deleteOldCpu1h = `-- name: DeleteOldCpu1h :exec
DELETE FROM metrics_cpu_1h WHERE time_bucket < $1
`

func (q *Queries) DeleteOldCpu1h(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldCpu1h, threshold)
	return err
}

const deleteOldCpu1m = `-- name: DeleteOldCpu1m :exec
DELETE FROM metrics_cpu_1m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldCpu1m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldCpu1m, threshold)
	return err
}

const deleteOldCpu5m = `-- name: DeleteOldCpu5m :exec
DELETE FROM metrics_cpu_5m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldCpu5m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldCpu5m, threshold)
	return err
}

const deleteOldCpuRaw = `-- name: DeleteOldCpuRaw :exec
DELETE FROM metrics_cpu_raw WHERE time < $1
`

func (q *Queries) DeleteOldCpuRaw(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldCpuRaw, threshold)
	return err
}

const deleteOldDisk10m = `-- name: DeleteOldDisk10m :exec
DELETE FROM metrics_disk_10m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDisk10m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDisk10m, threshold)
	return err
}

const deleteOldDisk1d = `-- name: DeleteOldDisk1d :exec
DELETE FROM metrics_disk_1d WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDisk1d(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDisk1d, threshold)
	return err
}

const deleteOldDisk1h = `-- name: DeleteOldDisk1h :exec
DELETE FROM metrics_disk_1h WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDisk1h(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDisk1h, threshold)
	return err
}

const deleteOldDisk1m = `-- name: DeleteOldDisk1m :exec
DELETE FROM metrics_disk_1m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDisk1m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDisk1m, threshold)
	return err
}

const deleteOldDisk5m = `-- name: DeleteOldDisk5m :exec
DELETE FROM metrics_disk_5m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDisk5m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDisk5m, threshold)
	return err
}

const deleteOldDiskRaw = `-- name: DeleteOldDiskRaw :exec
DELETE FROM metrics_disk_raw WHERE time < $1
`

func (q *Queries) DeleteOldDiskRaw(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDiskRaw, threshold)
	return err
}

const deleteOldDocker10m = `-- name: DeleteOldDocker10m :exec
DELETE FROM metrics_docker_10m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDocker10m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDocker10m, threshold)
	return err
}

const deleteOldDocker1d = `-- name: DeleteOldDocker1d :exec
DELETE FROM metrics_docker_1d WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDocker1d(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDocker1d, threshold)
	return err
}

const deleteOldDocker1h = `-- name: DeleteOldDocker1h :exec
DELETE FROM metrics_docker_1h WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDocker1h(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDocker1h, threshold)
	return err
}

const deleteOldDocker1m = `-- name: DeleteOldDocker1m :exec
DELETE FROM metrics_docker_1m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDocker1m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDocker1m, threshold)
	return err
}

const deleteOldDocker5m = `-- name: DeleteOldDocker5m :exec
DELETE FROM metrics_docker_5m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldDocker5m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDocker5m, threshold)
	return err
}

const deleteOldDockerRaw = `-- name: DeleteOldDockerRaw :exec
DELETE FROM metrics_docker_raw WHERE time < $1
`

func (q *Queries) DeleteOldDockerRaw(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDockerRaw, threshold)
	return err
}

const deleteOldNetwork10m = `-- name: DeleteOldNetwork10m :exec
DELETE FROM metrics_network_10m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldNetwork10m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldNetwork10m, threshold)
	return err
}

const deleteOldNetwork1d = `-- name: DeleteOldNetwork1d :exec
DELETE FROM metrics_network_1d WHERE time_bucket < $1
`

func (q *Queries) DeleteOldNetwork1d(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldNetwork1d, threshold)
	return err
}

const deleteOldNetwork1h = `-- name: DeleteOldNetwork1h :exec
DELETE FROM metrics_network_1h WHERE time_bucket < $1
`

func (q *Queries) DeleteOldNetwork1h(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldNetwork1h, threshold)
	return err
}

const deleteOldNetwork1m = `-- name: DeleteOldNetwork1m :exec
DELETE FROM metrics_network_1m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldNetwork1m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldNetwork1m, threshold)
	return err
}

const deleteOldNetwork5m = `-- name: DeleteOldNetwork5m :exec
DELETE FROM metrics_network_5m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldNetwork5m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldNetwork5m, threshold)
	return err
}

const deleteOldNetworkRaw = `-- name: DeleteOldNetworkRaw :exec
DELETE FROM metrics_network_raw WHERE time < $1
`

func (q *Queries) DeleteOldNetworkRaw(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldNetworkRaw, threshold)
	return err
}

const deleteOldRam10m = `-- name: DeleteOldRam10m :exec
DELETE FROM metrics_ram_10m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldRam10m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRam10m, threshold)
	return err
}

const deleteOldRam1d = `-- name: DeleteOldRam1d :exec
DELETE FROM metrics_ram_1d WHERE time_bucket < $1
`

func (q *Queries) DeleteOldRam1d(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRam1d, threshold)
	return err
}

const deleteOldRam1h = `-- name: DeleteOldRam1h :exec
DELETE FROM metrics_ram_1h WHERE time_bucket < $1
`

func (q *Queries) DeleteOldRam1h(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRam1h, threshold)
	return err
}

const deleteOldRam1m = `-- name: DeleteOldRam1m :exec
DELETE FROM metrics_ram_1m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldRam1m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRam1m, threshold)
	return err
}

const deleteOldRam5m = `-- name: DeleteOldRam5m :exec
DELETE FROM metrics_ram_5m WHERE time_bucket < $1
`

func (q *Queries) DeleteOldRam5m(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRam5m, threshold)
	return err
}

const deleteOldRamRaw = `-- name: DeleteOldRamRaw :exec
DELETE FROM metrics_ram_raw WHERE time < $1
`

func (q *Queries) DeleteOldRamRaw(ctx context.Context, threshold pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRamRaw, threshold)
	return err
}

type InsertCpuRawParams struct {
	Time         pgtype.Timestamptz `json:"time"`
	AssetID      pgtype.UUID        `json:"asset_id"`
	UsagePercent pgtype.Float4      `json:"usage_percent"`
}

type InsertDiskRawParams struct {
	Time       pgtype.Timestamptz `json:"time"`
	AssetID    pgtype.UUID        `json:"asset_id"`
	Device     pgtype.Text        `json:"device"`
	UsedBytes  pgtype.Int8        `json:"used_bytes"`
	TotalBytes pgtype.Int8        `json:"total_bytes"`
}

type InsertDockerRawParams struct {
	Time            pgtype.Timestamptz `json:"time"`
	ContainerID     pgtype.UUID        `json:"container_id"`
	CpuUsagePercent pgtype.Float4      `json:"cpu_usage_percent"`
	RamUsedBytes    pgtype.Int8        `json:"ram_used_bytes"`
}

type InsertNetworkRawParams struct {
	Time      pgtype.Timestamptz `json:"time"`
	AssetID   pgtype.UUID        `json:"asset_id"`
	Interface pgtype.Text        `json:"interface"`
	RxBytes   pgtype.Int8        `json:"rx_bytes"`
	TxBytes   pgtype.Int8        `json:"tx_bytes"`
}

type InsertRamRawParams struct {
	Time       pgtype.Timestamptz `json:"time"`
	AssetID    pgtype.UUID        `json:"asset_id"`
	UsedBytes  pgtype.Int8        `json:"used_bytes"`
	TotalBytes pgtype.Int8        `json:"total_bytes"`
}
